#!/usr/bin/env bash
rotate() {
    degree="$1"
    tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
	case "$(file -b -i "$file")" in
	    image/jpeg*)
		jpegtran -rotate "$degree" -copy all -outfile "$file" "$file"
	    ;;
	    *)
		mogrify  -rotate "$degree" "$file" ;;
        esac
    done
}

while read file
do
    case "$1" in
        "c")
            xclip -selection clipboard -target image/png "$file" &&
            notify-send "$file has been copied to clipboard." && exit 0
        ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] &&
            rm "$file" && notify-send "$file deleted."
        ;;
        "g")
            pacman -Qq "gimpr" >/dev/null 2>&1 && gimp "$file" ||
            notify-send "ERROR" "\nGimp is not installed! Install gimp if you want to use this function in sxiv:\n\nsudo package-manager-install-command gimp" &&
            exit 1;
        ;;
        "i")
            notify-send "File information" \
            "$(mediainfo "$file" | tr -s ' ' | grep -v CompleteName_Last)"
        ;;
        "x")
            setwall.sh $file &&
            filename=$HOME/.cache/wall
            if [ ! -f $filename ]; then
                touch $filename
            fi
            echo "$file" > $HOME/.cache/wall &&
            notify-send "$file has been set as your wallpaper." && exit 0
        ;;
        "7")
            rotate 270
        ;;
        "8")
            rotate 180
        ;;
        "9")
            rotate 90
        ;;
        esac
done
