#!/usr/bin/env bash
#### AUTOSTART ####
sxhkd &
killall nm-applet & sleep 1 && nm-applet &
killall volumeicon & sleep 1 && volumeicon &
/usr/bin/emacs --daemon &
killall polybar & sleep 1 && polybar &

#### MONITORS ####
for monitor in $(bspc query -M)
do
    # set the workspaces on each monitor to 1-9
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9 10
    #polybar hidden when fullscreen for vlc, youtube, mpv ...
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
done

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  1
bspc config window_gap                    8
bspc config top_padding                   0
bspc config bottom_padding                20
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color         "#4c566a"
bspc config active_border_color		"#005577"
bspc config focused_border_color	    "#5e81ac"
bspc config presel_feedback_color	    "#5e81ac"
bspc config urgent_border_color 	    "#dd2727"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Microsoft-edge desktop='^2'
bspc rule -a yad state=floating focus=on
