# import = ["/home/firmanqs/.cache/wal/alacritty-pywal.toml"]
[colors.primary]
background = "#000000"
foreground = "#bbc2cf"

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.8
